#!/usr/bin/env bash

# Remove user-local installation

sudo rm -R ~/Library/Google/GoogleSoftwareUpdate/

sudo touch ~/Library/Google/GoogleSoftwareUpdate
sudo chmod 444 ~/Library/Google/GoogleSoftwareUpdate

sudo rm ~/Library/LaunchAgents/com.google.keystone.agent.plist
sudo rm  -R ~/Library/Caches/com.google.Keystone*
sudo rm ~/Library/Preferences/com.google.Keystone.Agent.plist

# Remove system-level installation

sudo rm -R /Library/Google/GoogleSoftwareUpdate/

sudo touch /Library/Google/GoogleSoftwareUpdate
sudo chmod 444 /Library/Google/GoogleSoftwareUpdate

sudo rm /Library/LaunchAgents/com.google.keystone.agent.plist
sudo rm  -R /Library/Caches/com.google.Keystone*
sudo rm /Library/Preferences/com.google.Keystone.Agent.plist
