#!/usr/bin/env sh

get_abs_path() { echo "$(cd "$(dirname "$1")"; pwd)/$(basename "$1")"; }

args="";
watch_dir="";

if [[ $1 == "help" ]] || [[ $1 = "--help" ]]; then
  watchexec --help | grep -A 3 "OPTIONS:";
  return;
else
  if [[ $1 == "-w" ]]; then
    watch_dir=get_abs_path $2;
  else
    watch_dir=$(pwd);
  fi
 args='--filter "*/docker-compose.yml"' && [[ $1 ]] && args=$@;
fi

echo "Watching for changes in " $watch_dir;

eval watchexec --restart $args -w $watch_dir "docker-compose up";
