;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-skip-close-maybe
        c-electric-brace
        c-electric-lt-gt
        c-electric-pound
        c-electric-semi&comma
        c-electric-slash
        c-indent-line-or-region
        downcase-region
        elpy-nav-forward-indent
        find-corresponding-file
        forward-kill-word
        haskell-indentation-common-electric-command
        indent-for-tab-command
        keyboard-escape-quit
        kill-region
        markdown-exdent-or-delete
        my/forward-delete-word
        my/util/backward-delete-word
        save-all-buffers
        save-some-buffers
        string-inflection-all-cycle
        upcase-region
        yaml-electric-dash-and-dot
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-colon
        c-electric-paren
        c-electric-star
        c-indent-new-comment-line
        dired-next-line
        dired-previous-line
        goto-line
        kill-this-buffer
        my/backward-delete-word
        overwrite-mode
        toggle-comment-region-or-line
        ))
