;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	autopair-insert-opening
	autopair-insert-or-skip-quote
	autopair-skip-close-maybe
	c-electric-pound
	c-electric-semi&comma
	find-corresponding-file
	indent-for-tab-command
	keyboard-escape-quit
	kill-region
	save-some-buffers
	))

(setq mc/cmds-to-run-once
      '(
	c-electric-colon
	c-electric-paren
	c-electric-star
	kill-this-buffer
	overwrite-mode
	toggle-comment-region-or-line
	))
